equipment-costs:
  DIAMOND_HELMET: 5
  DIAMOND_CHESTPLATE: 8
  DIAMOND_LEGGINGS: 7
  DIAMOND_BOOTS: 4
  DIAMOND_SWORD: 10
mob-equipment:
  ZOMBIE:
    HEAD: DIAMOND_HELMET
    CHEST: DIAMOND_CHESTPLATE
    LEGS: DIAMOND_LEGGINGS
    FEET: DIAMOND_BOOTS
    HAND: DIAMOND_SWORD
  SKELETON:
    HEAD: DIAMOND_HELMET
    CHEST: DIAMOND_CHESTPLATE
    LEGS: DIAMOND_LEGGINGS
    FEET: DIAMOND_BOOTS
    HAND: DIAMOND_SWORD
